sso login script fixes and ignoring some helper scripts

diff --git a/bin/saws-sso-login b/bin/saws-sso-login
--- a/bin/saws-sso-login
+++ b/bin/saws-sso-login
@@ -1,3 +1,18 @@
 #!/usr/bin/env zsh
 
-aws sso login --profile "$(rg '\[profile (.+)\]' ~/.aws/config -r '$1' | fzf --header 'SSO login to selected ENV')"
+profile="$(rg '\[profile (.+)\]' ~/.aws/config -r '$1' | fzf --header 'SSO login to selected ENV')"
+exit_code=$?
+
+case $exit_code in
+  1)
+    echo "Could not find matching profile"
+    exit 1
+    ;;
+  130)
+    echo "Canceling..."
+    exit 1
+    ;;
+  0)
+    aws sso login --profile "$profile"
+    ;;
+esac
